[package]
name = "spdlog_bridge"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"